%YAML 1.2
%TAG !n! tag:nimyaml.org,2016:
--- !n!custom:Config 
startintro: false
startapp: false
installOs: "none"
nographics: false
spice: false
introspect: "looking-glass"
shareddir: !!null ~
spicePort: 5900
sshPort: 2222
connectivity: 
  exposedPorts: []
container: 
  kernel: windows.arc
  state: []
  initialSize: 20
  iso: !!null ~
cpus: 
  cores: 8
  sockets: 1
  threads: 2
  ramAlloc: 4000
gpus: []
nics: []
root: ~/.local/libvf.io
sudo: false
commands: []
startupCommands: []
teardownCommands: []
installCommands: []
appCommands: 
  - 
    is_root: true
    list: 
      - 
        exec: echo
        args: [hello, world]
